analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "ios/**"
    - "android/**"
    - "**/generated/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
  errors:
    todo: ignore  # 忽略 TODO 注释的检测