name: sona
description: an AI persona dating app.
publish_to: 'none'

version: 1.1.0+32

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
#  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  intl_phone_field: ^3.2.0
  pinput: ^2.2.31
  appinio_swiper: ^2.1.0
  fluttertoast: ^8.2.2
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.0.1
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  crop_your_image: ^0.7.5
  infinite_scroll_pagination: ^4.0.0
  geolocator: ^10.1.0
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5
  firebase_messaging: ^14.7.16
  firebase_auth: ^4.17.5
  firebase_analytics: ^10.8.6
  firebase_crashlytics: ^3.4.15
  firebase_app_check: ^0.2.1+14
  flutter_local_notifications: ^16.3.2
  lottie:
  in_app_purchase: ^3.1.13
  stacked_page_view: ^1.1.2
  flutter_image_compress: ^2.0.4
  webview_flutter: ^4.2.4
  hive: ^2.2.3
  hive_flutter:
  flutter_cache_manager: ^3.3.1
  rxdart: ^0.27.7
  url_launcher: ^6.1.14
  package_info_plus: ^5.0.1
#  appsflyer_sdk: ^6.12.2
  riverpod_annotation: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0
  google_mlkit_face_detection: ^0.9.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  system_settings: ^2.1.0
  uuid: ^4.2.2
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  image: ^4.1.7
  video_player: ^2.8.2

  gal:
  path_provider:
  image_editor: ^1.3.0
  share_plus: ^7.2.2
dev_dependencies:
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  build_runner:
  arb_generator: ^0.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: 'M PLUS Rounded 1c'
      fonts:
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Black.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-ExtraBold.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Bold.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Medium.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Regular.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Light.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Thin.ttf
  assets:
    - assets/
    - assets/fonts/m_plus_rounded_1c/
    - assets/i18n/
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/videos/
    - assets/svg/
    - assets/apng/

# dart run arb_generator
arb_generator:
  input_filepath: "assets_dev/i18n.csv"
  output_directory: "lib/l10n"
  filename_prepend: "intl_"

flutter_intl:
  enabled: true
