name: sona
description: an AI persona dating app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
#  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  intl_phone_field: ^3.2.0
  pinput: ^2.2.31
  appinio_swiper: ^2.0.2
  tencent_cloud_chat_sdk: ^5.1.8
  fluttertoast: ^8.2.2
  flutter_easyloading: ^3.0.5
  permission_handler: ^10.4.3
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in:
  extended_image:


dev_dependencies:
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
   - assets/
