name: sona
description: an AI persona dating app.
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
#  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  intl_phone_field: ^3.2.0
  pinput: ^2.2.31
  appinio_swiper: ^2.0.2
  fluttertoast: ^8.2.2
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.0.1
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  crop_your_image: ^0.7.5
  infinite_scroll_pagination: ^4.0.0
  geolocator: ^10.0.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  firebase_messaging: ^14.6.8
  firebase_auth: ^4.10.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.1
  lottie:
  in_app_purchase: ^3.1.10
  stacked_page_view: ^1.1.2
  flutter_image_compress: ^2.0.4
  webview_flutter: ^4.2.4
  hive: ^2.2.3
  hive_flutter:
  flutter_cache_manager: ^3.3.1
dev_dependencies:
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
    - assets/images/
