name: sona
description: an AI persona dating app.
publish_to: 'none'

version: 1.1.3+54

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
#  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  intl_phone_field: ^3.2.0
  pinput: ^5.0.2
  appinio_swiper: ^2.1.0
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.0.1
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  crop_your_image: ^0.7.5
  infinite_scroll_pagination: ^4.0.0
  geolocator: ^14.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_auth: ^6.0.2
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  firebase_app_check: ^0.4.0+1
  flutter_local_notifications: ^19.4.2
  lottie:
  in_app_purchase: ^3.1.13
  stacked_page_view: ^1.1.2
  flutter_image_compress: ^2.0.4
  webview_flutter: ^4.2.4
  hive: ^2.2.3
  hive_flutter:
  flutter_cache_manager: ^3.3.1
  rxdart: ^0.27.7
  url_launcher: ^6.1.14
  package_info_plus: ^9.0.0
  #  appsflyer_sdk: ^6.12.2
  riverpod_annotation: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0
#  google_mlkit_face_detection: ^0.9.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
#  system_settings: ^2.1.0
#  system_settings:
#    path: "../system_settings"
  uuid: ^4.2.2
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  image: ^4.1.7
  video_player: ^2.8.2
  record: ^6.0.0
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  gal:
  image_editor: ^1.3.0
  share_plus: ^7.2.2
  facebook_app_events: ^0.20.1
#  facebook_app_events:
#    git:
#      url: https://github.com/oddbit/flutter_facebook_app_events
#      ref: 3e4e062ded3eb92b37e43c274ee84da4a21edfa2
  proximity_sensor: ^1.0.4
  flutter_tts: ^4.0.2
dev_dependencies:
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  build_runner:
  arb_generator: ^0.0.3

dependency_overrides:
  record_darwin: ^1.0.1-beta.1
  smart_auth: ^3.2.0
  package_info_plus: ^9.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: 'M PLUS Rounded 1c'
      fonts:
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Black.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-ExtraBold.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Bold.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Medium.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Regular.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Light.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Thin.ttf
  assets:
    - assets/
    - assets/fonts/m_plus_rounded_1c/
    - assets/i18n/
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/videos/
    - assets/svg/
    - assets/apng/

# dart run arb_generator
arb_generator:
  input_filepath: "assets_dev/i18n.csv"
  output_directory: "lib/l10n"
  filename_prepend: "intl_"

flutter_intl:
  enabled: true
