name: sona
description: an AI persona dating app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # A
  appinio_swiper: ^2.1.0
  audioplayers: ^6.5.1
  #arb_generator: ^0.0.4

  #17878301579950
  # C
  cached_network_image: ^3.2.3
  cloud_firestore: ^6.0.1
#  crop_your_image: ^0.7.5
  cupertino_icons: ^1.0.2

  # D
  dio: ^5.3.0
  dotted_border: ^2.1.0

  # F
  facebook_app_events: ^0.20.1
  firebase_analytics: ^12.0.1
  firebase_app_check: ^0.4.0+1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter_cache_manager: ^3.3.1
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.18.6
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^19.4.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_card_swiper: ^7.0.2
  flutter_firebase_chat_core:
    git:
      url: git@github.com:zhangyc/flutter_firebase_chat_core.git
      branch: main
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  file_picker: ^8.0.3
  faker: ^2.1.0


  #  flutter_tts: ^4.2.3

  # G
  gal:
  geolocator: ^14.0.2
  google_sign_in: ^7.1.1
  go_router: ^16.2.0
  geocoding: ^4.0.0

  # H
  hive: ^2.2.3
  hive_flutter:
  hooks_riverpod: ^2.3.6

  # I
  image: ^4.1.7
  image_editor: ^1.3.0
  image_picker: ^1.0.2
  in_app_purchase: ^3.1.13
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0

  # L
  lottie:

  # O
  open_filex: ^4.4.0

  # P
  package_info_plus: ^9.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  pinput: ^5.0.2
  proximity_sensor: ^1.0.4
  photo_view: ^0.15.0

  # R
  record: ^6.1.1
  rxdart: ^0.28.0


  # S
  shared_preferences: ^2.2.0
  share_plus: ^7.2.2
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.1.0
  stacked_page_view: ^1.1.2
  sweph: ^3.2.1+2.10.3

  #m
  mime: ^1.0.5


  # U
  url_launcher: ^6.1.14
  uuid: ^4.2.2

  # V
  video_player: ^2.10.0

  # W
  webview_flutter: ^4.2.4
  wukongimfluttersdk: ^1.6.7

  # 注释掉的依赖
  #  appsflyer_sdk: ^6.12.2
  #  facebook_app_events:
  #    git:
  #      url: https://github.com/oddbit/flutter_facebook_app_events
  #      ref: 3e4e062ded3eb92b37e43c274ee84da4a21edfa2
  #  firebase_core: ^2.15.0
  #  google_mlkit_face_detection: ^0.9.0
  #  system_settings: ^2.1.0
  #  system_settings:
  #    path: "../system_settings"

dev_dependencies:
  custom_lint: 
  flutter_lints: 
  riverpod_lint: ^2.6.5
  build_runner: ^2.6.0
  go_router_builder: ^4.0.1
  arb_generator: ^0.0.4


dependency_overrides:
  package_info_plus: ^9.0.0
  record_darwin: ^1.2.2
flutter:
  uses-material-design: true
  fonts:
    - family: 'M PLUS Rounded 1c'
      fonts:
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Black.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-ExtraBold.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Bold.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Medium.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Regular.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Light.ttf
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Thin.ttf
  assets:
    - assets/
    - assets/fonts/m_plus_rounded_1c/
    - assets/i18n/
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/videos/
    - assets/svg/
    - assets/apng/
    - assets/app/
    - assets/fonts/
    - assets/ephe/
    - assets/test/
    - assets/match/
    - assets/home/

# dart run arb_generator
arb_generator:
  input_filepath: "assets_dev/i18n.csv"
  output_directory: "lib/l10n"
  filename_prepend: "intl_"

flutter_intl:
  enabled: true
